### ISSUE TITLE
License

### ISSUE THREAD

**Issue by malb** [sagemath/cysignals#2]
This code is licensed under the GNU General Public License version 2 or later. We might want to consider relicense under the 2-clause BSD license to enable more projects to use this code (e.g. numerical packages which tend to prefer BSD)

The code references the following copyright holders:

- Martin Albrecht @malb
- William Stein @wstein
- Jeroen Demeyer @jdemeyer

`git log` in the relevant Sage directory also points to

- François Bissey @kiwifb

Also

- Volker Braun @vbraun

**Comment by malb** [comment]
To make my consent explicit: I support relicensing under the 2-clause BSD license.

**Comment by jdemeyer** [comment]
Sorry, but I like the philosophy of the GPL. I'm not saying that I cannot be convinced, but there has to be a good reason.

**Comment by jdemeyer** [comment]
I'm pretty sure that @vbraun is also a significant author.

**Comment by kiwifb** [comment]
While I am philosophically more inclined to choose GPL, I am pragmatic. If licensing under GPL make it difficult to ship alongside `numpy`/`scipy`/`matplotlib` and friends I wouldn't have any objection for my mediocre contributions that have mostly been replaced by Jeroen to be licensed under a BSD license.

**Comment by vbraun** [comment]
I agree with Francois; Personally I prefer GPL but if (is it?) numpy/scipy/... wants to depend on it then I'm fine with BSD / dual license.

**Comment by jdemeyer** [comment]
Two questions:

1. Are people *using* this package forced to GPL their package in the first place? I guess they do, since importing a Python module is analogous to dynamic linking)

2. Are we forced to stick with the GPL because Cython is GPL? After all, we are relying on interfaces provided by Cython. This only happens at compile-time but it's not that different from static linking.

**Comment by malb** [comment]
Shall we do a poll:

- GPL
- 2-clause BSD
- LGPL
- Apache License 2.0

where **+1** means "yes, please", **0** means "I'm okay with that, but not eager", **-1** means "I do not accept this one"?

**Comment by jdemeyer** [comment]
After thinking about this, I would go for [LGPL v3](http://www.gnu.org/licenses/lgpl.html) or later. That should be sufficient for other software to use this package, which still being copyleft.

**Comment by kiwifb** [comment]
The only one that I wouldn't be OK with is Apache. I would be quite happy with LGPL.

**Comment by malb** [comment]
I'm okay with LGPL v3 or later as well.

**Comment by certik** [comment]
I suggested to relicense to BSD on William Stein's G+: https://plus.google.com/u/0/115360165819500279592/posts/Deup3aK6v8k, to be aligned with the permissive licensing of Python, Cython, SciPy and similar packages, because I thought it would make sense for a relatively small package like this one. The code here is essentially an extension of Cython that every Cython user hits eventually, that a C or C++ code can't be interrupted with CTRL-C from Python, which is a real pain.

But I fully respect @jdemeyer and @vbraun's work to implement this, and they have the right to choose the license.

**Comment by williamstein** [comment]
I am OK with any license.  I think @jdemeyer did **by far** the most work on this and he is happy with LGPL v3, so that seems like the way to go.

**Comment by vbraun** [comment]
Fine with me

**Comment by malb** [comment]
This settles it then. Let's update the license, tag release 0.9 and cross our fingers switching over Sage is painless.
