### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by videlec** [sagemath/cysignals#63]
Because windows does not support POSIX signals, the current cysignals does not work on this platform. However, windows handles the floating-point exception (SIGFPE) similarly to POSIX signals. Using this fact, [cypari](https://bitbucket.org/t3m/cypari) provides a fork of cysignals that works on windows. See the explanation at [line 372 in implementation.c](https://bitbucket.org/t3m/cypari/src/75e588eac5683484c4c43cb428123aa422534012/Version2/cypari_src/implementation.c?at=default&fileviewer=file-view-default#implementation.c-372). This special handling for windows only concerns windows and the code remains unchanged for other platforms.

A windows port would benefit to several Python libraries that want support for windows (e.g. [giacpy](https://gitlab.math.univ-paris-diderot.fr/han/giacpy), [cypari2](https://github.com/defeo/cypari2)).

**Comment by johnyf** [comment]
As a sidenote, it appears that `cysignals` works using Cygwin:

https://github.com/sagemath/cysignals/blob/acc2ba9fcf8ffa3db1c0f1cf0da8deae7035f41d/setup.py#L34-L37

**Comment by jdemeyer** [comment]
> As a sidenote, it appears that cysignals works using Cygwin:

Yes, it does.

**Comment by vinklein** [comment]
Hi, 
I am currently working on this subject and have a first compiling prototype/draft ([cysignals_windows_version](https://github.com/vinklein/cysignals/commits/cysignals_windows_version)).

I am currently looking to translate tests.pyx for windows, it's uneasy because of the lack of proper `fork `and `kill` (Send signal manually) equivalents in windows. 

@jdemeyer What's the best way / hack to do a Cython `#if defined(_WIN32)` ? i have found this old topic https://groups.google.com/forum/#!topic/cython-users/HASNraxsGGw but you may have more recent way to do this.

**Comment by vinklein** [comment]
[Here](https://github.com/vinklein/cysignals/wiki/How-to-install-cysignals-on-Windows) is a first step-by-step guide to install cysignals on windows in case if someone want to test the current [windows_dev](https://github.com/vinklein/cysignals/commits/windows_dev).

**Comment by jdemeyer** [comment]
Hello Vincent. It's not clear to me if you expect some feedback at this time.

If you are serious in porting cysignals to Windows, you really need to set up continuous integration (on Windows, this is typically done by Appveyor).

**Comment by vinklein** [comment]
Hello Jeroen. Yes feedback is welcome at this point.

> If you are serious in porting cysignals to Windows, you really need to set up continuous integration (on Windows, this is typically done by Appveyor).

I will look at it. Thanks.
